Write a function standardize(a) that takes a two dimensional NumPy array of floats and returns an array of the same shape in which every column has zero mean and unit standard deviation.

For each column, subtract the mean of that column and divide by the standard deviation of that column. Use the default np.std, that is ddof=0.

Use the axis argument together with broadcasting. Do not write a for or while loop and do not use a list comprehension. You may assume that no column is constant.

For example, for
a = np.array([[1.0, 2.0],
              [3.0, 6.0],
              [5.0, 10.0]])
standardize(a) returns
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]

Write your program below:

In [ ]:
import numpy as np

def standardize(a):
    mean = np.mean(a, axis=0)
    std = np.std(a, axis=0)
    return (a - mean) / std

Write a function circle_grid(n, r) that does the following.

Build a square grid of n * n points by taking np.linspace(-1, 1, n) along both axes and passing it to np.meshgrid. Then return the number of grid points (x, y) that satisfy
x2 + y2 ≤ r2

Use a boolean mask to do the counting. Do not write a for or while loop and do not use a list comprehension.

For example, circle_grid(3, 1.0) returns 5: of the nine grid points, the four corners lie outside the unit circle and the remaining five lie on or inside it. Note that the boundary counts, so the comparison is ≤ and not <.

Write your program below:

In [ ]:
import numpy as np

def circle_grid(n, r):
    x = np.linspace(-1, 1, n)
    y = np.linspace(-1, 1, n)
    X, Y = np.meshgrid(x, y)

    mask = X**2 + Y**2 <= r**2
    return np.sum(mask)

Write a function fit_line(x, y) that fits the straight line
y = m x + c

to the data in the one dimensional arrays x and y in the least squares sense, and returns the tuple (m, c) of two numbers, slope first.

Build the design matrix whose first column is x and whose second column is np.ones_like(x), and pass it to np.linalg.lstsq with rcond=None. Remember that lstsq returns a tuple whose first element is the solution vector.

Do not use np.polyfit, scipy or any other fitting routine.

For example, for x = [0, 1, 2, 3, 4] and y = [2, 5, 8, 11, 14] the answer is (3.0, 2.0).

Write your program below:

In [1]:
import numpy as np

def fit_line(x, y):
    A = np.column_stack((x, np.ones_like(x)))
    solution = np.linalg.lstsq(A, y, rcond=None)[0]
    m, c = solution
    return (m, c)

Write a function distance_matrix(points) that takes an array of shape (n, 2) holding the coordinates of n points in the plane, and returns the array D of shape (n, n) whose entry D[i, j] is the Euclidean distance between point i and point j.

Use np.newaxis (or None) and broadcasting. Do not write a for or while loop, do not use a list comprehension, and do not use scipy.

For example, for the points [[0, 0], [3, 0], [0, 4]] the result is
[[0. 3. 4.]
 [3. 0. 5.]
 [4. 5. 0.]]

Write your program below:

In [2]:
import numpy as np

def distance_matrix(points):
    diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]
    D = np.sqrt(np.sum(diff**2, axis=2))
    return D

Write a function interleave(a, b) that takes two one dimensional NumPy arrays of the same length n and returns a single one dimensional array of length 2 * n whose entries alternate between the two inputs, starting with a:
a[0], b[0], a[1], b[1], ..., a[n-1], b[n-1]
Build it with np.stack (or np.column_stack) followed by a reshape or a ravel. Do not write a for or while loop and do not use a list comprehension.

For example, interleave(np.array([1, 2, 3]), np.array([4, 5, 6])) returns array([1, 4, 2, 5, 3, 6]).

Write your program below:

In [3]:
import numpy as np

def interleave(a, b):
    return np.column_stack((a, b)).ravel()